[package]
name = "rust_bfcompiler"
version = "1.0.0"
authors = ["TheEyeOfAr3s"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.6"
